# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0003_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='author',
            new_name='user',
        ),
    ]
